# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'birdWindow.ui'
#
# Created: Wed Sep 23 20:29:56 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BirdWindow(object):
    def setupUi(self, BirdWindow):
        BirdWindow.setObjectName(_fromUtf8("BirdWindow"))
        BirdWindow.resize(588, 440)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cute_bird3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BirdWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(BirdWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.quitButton = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cute_bird.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon1)
        self.quitButton.setIconSize(QtCore.QSize(79, 88))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.gridlayout.addWidget(self.quitButton, 0, 0, 3, 1)
        self.showFilesButton = QtGui.QPushButton(self.centralwidget)
        self.showFilesButton.setObjectName(_fromUtf8("showFilesButton"))
        self.gridlayout.addWidget(self.showFilesButton, 0, 1, 1, 2)
        self.showPlotButton = QtGui.QPushButton(self.centralwidget)
        self.showPlotButton.setObjectName(_fromUtf8("showPlotButton"))
        self.gridlayout.addWidget(self.showPlotButton, 1, 1, 1, 2)
        self.showBtfButton = QtGui.QPushButton(self.centralwidget)
        self.showBtfButton.setObjectName(_fromUtf8("showBtfButton"))
        self.gridlayout.addWidget(self.showBtfButton, 2, 1, 1, 2)
        self.smallCalcButton = QtGui.QPushButton(self.centralwidget)
        self.smallCalcButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.smallCalcButton.setObjectName(_fromUtf8("smallCalcButton"))
        self.gridlayout.addWidget(self.smallCalcButton, 3, 0, 1, 1)
        self.showDataButton = QtGui.QPushButton(self.centralwidget)
        self.showDataButton.setObjectName(_fromUtf8("showDataButton"))
        self.gridlayout.addWidget(self.showDataButton, 3, 1, 1, 2)
        self.showOptButton = QtGui.QPushButton(self.centralwidget)
        self.showOptButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.showOptButton.setObjectName(_fromUtf8("showOptButton"))
        self.gridlayout.addWidget(self.showOptButton, 4, 0, 1, 1)
        self.enrPlusButton = QtGui.QPushButton(self.centralwidget)
        self.enrPlusButton.setMaximumSize(QtCore.QSize(38, 27))
        self.enrPlusButton.setObjectName(_fromUtf8("enrPlusButton"))
        self.gridlayout.addWidget(self.enrPlusButton, 4, 1, 1, 1)
        self.enrMinusButton = QtGui.QPushButton(self.centralwidget)
        self.enrMinusButton.setMaximumSize(QtCore.QSize(38, 27))
        self.enrMinusButton.setObjectName(_fromUtf8("enrMinusButton"))
        self.gridlayout.addWidget(self.enrMinusButton, 4, 2, 1, 1)
        self.btfEnvelopLabel = QtGui.QLabel(self.centralwidget)
        self.btfEnvelopLabel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.btfEnvelopLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.btfEnvelopLabel.setObjectName(_fromUtf8("btfEnvelopLabel"))
        self.gridlayout.addWidget(self.btfEnvelopLabel, 5, 0, 1, 1)
        self.btfEnvelopMode = QtGui.QComboBox(self.centralwidget)
        self.btfEnvelopMode.setObjectName(_fromUtf8("btfEnvelopMode"))
        self.gridlayout.addWidget(self.btfEnvelopMode, 5, 1, 1, 2)
        self.fintEnvelopLabel = QtGui.QLabel(self.centralwidget)
        self.fintEnvelopLabel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.fintEnvelopLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fintEnvelopLabel.setObjectName(_fromUtf8("fintEnvelopLabel"))
        self.gridlayout.addWidget(self.fintEnvelopLabel, 6, 0, 1, 1)
        self.fintEnvelopMode = QtGui.QComboBox(self.centralwidget)
        self.fintEnvelopMode.setObjectName(_fromUtf8("fintEnvelopMode"))
        self.gridlayout.addWidget(self.fintEnvelopMode, 6, 1, 1, 2)
        self.bowLabel = QtGui.QLabel(self.centralwidget)
        self.bowLabel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.bowLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bowLabel.setObjectName(_fromUtf8("bowLabel"))
        self.gridlayout.addWidget(self.bowLabel, 7, 0, 1, 1)
        self.channelBow = QtGui.QComboBox(self.centralwidget)
        self.channelBow.setObjectName(_fromUtf8("channelBow"))
        self.gridlayout.addWidget(self.channelBow, 7, 1, 1, 2)
        self.vboxlayout.addLayout(self.gridlayout)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.vhiLabel = QtGui.QLabel(self.centralwidget)
        self.vhiLabel.setMaximumSize(QtCore.QSize(90, 18))
        self.vhiLabel.setObjectName(_fromUtf8("vhiLabel"))
        self.gridlayout1.addWidget(self.vhiLabel, 0, 0, 1, 1)
        self.voiLabel = QtGui.QLabel(self.centralwidget)
        self.voiLabel.setMaximumSize(QtCore.QSize(90, 18))
        self.voiLabel.setObjectName(_fromUtf8("voiLabel"))
        self.gridlayout1.addWidget(self.voiLabel, 0, 1, 1, 1)
        self.expLabel = QtGui.QLabel(self.centralwidget)
        self.expLabel.setMaximumSize(QtCore.QSize(90, 18))
        self.expLabel.setObjectName(_fromUtf8("expLabel"))
        self.gridlayout1.addWidget(self.expLabel, 0, 2, 1, 1)
        self.vhiChoice = PointSpinBox(self.centralwidget)
        self.vhiChoice.setObjectName(_fromUtf8("vhiChoice"))
        self.gridlayout1.addWidget(self.vhiChoice, 1, 0, 1, 1)
        self.voiChoice = PointSpinBox(self.centralwidget)
        self.voiChoice.setObjectName(_fromUtf8("voiChoice"))
        self.gridlayout1.addWidget(self.voiChoice, 1, 1, 1, 1)
        self.expChoice = PointSpinBox(self.centralwidget)
        self.expChoice.setObjectName(_fromUtf8("expChoice"))
        self.gridlayout1.addWidget(self.expChoice, 1, 2, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.caseItem = QtGui.QComboBox(self.centralwidget)
        self.caseItem.setMaximumSize(QtCore.QSize(110, 16777215))
        self.caseItem.setObjectName(_fromUtf8("caseItem"))
        self.hboxlayout1.addWidget(self.caseItem)
        self.pointItem = QtGui.QSpinBox(self.centralwidget)
        self.pointItem.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pointItem.setMaximum(5000)
        self.pointItem.setObjectName(_fromUtf8("pointItem"))
        self.hboxlayout1.addWidget(self.pointItem)
        self.vboxlayout.addLayout(self.hboxlayout1)
        spacerItem = QtGui.QSpacerItem(20, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.hboxlayout.addLayout(self.vboxlayout)
        self.cellCanvas = CellCanvas(self.centralwidget)
        self.cellCanvas.setMinimumSize(QtCore.QSize(368, 370))
        self.cellCanvas.setObjectName(_fromUtf8("cellCanvas"))
        self.hboxlayout.addWidget(self.cellCanvas)
        BirdWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BirdWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPrint = QtGui.QMenu(self.menuFile)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/stock-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuPrint.setIcon(icon2)
        self.menuPrint.setObjectName(_fromUtf8("menuPrint"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        self.menuEnvelops = QtGui.QMenu(self.menuWindows)
        self.menuEnvelops.setObjectName(_fromUtf8("menuEnvelops"))
        BirdWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BirdWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BirdWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(BirdWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/Jolly-Roger.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionShowFiles = QtGui.QAction(BirdWindow)
        self.actionShowFiles.setObjectName(_fromUtf8("actionShowFiles"))
        self.actionShowPlot = QtGui.QAction(BirdWindow)
        self.actionShowPlot.setObjectName(_fromUtf8("actionShowPlot"))
        self.actionShowBTF = QtGui.QAction(BirdWindow)
        self.actionShowBTF.setObjectName(_fromUtf8("actionShowBTF"))
        self.actionShowData = QtGui.QAction(BirdWindow)
        self.actionShowData.setObjectName(_fromUtf8("actionShowData"))
        self.actionShowOpt = QtGui.QAction(BirdWindow)
        self.actionShowOpt.setObjectName(_fromUtf8("actionShowOpt"))
        self.actionBTF_Envelop = QtGui.QAction(BirdWindow)
        self.actionBTF_Envelop.setObjectName(_fromUtf8("actionBTF_Envelop"))
        self.actionFint_Envelop = QtGui.QAction(BirdWindow)
        self.actionFint_Envelop.setObjectName(_fromUtf8("actionFint_Envelop"))
        self.actionPrint = QtGui.QAction(BirdWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionPrint_Pin_Layout = QtGui.QAction(BirdWindow)
        self.actionPrint_Pin_Layout.setObjectName(_fromUtf8("actionPrint_Pin_Layout"))
        self.actionPrint_Diagram = QtGui.QAction(BirdWindow)
        self.actionPrint_Diagram.setObjectName(_fromUtf8("actionPrint_Diagram"))
        self.actionPrint_Data_text = QtGui.QAction(BirdWindow)
        self.actionPrint_Data_text.setObjectName(_fromUtf8("actionPrint_Data_text"))
        self.menuPrint.addAction(self.actionPrint_Pin_Layout)
        self.menuPrint.addAction(self.actionPrint_Diagram)
        self.menuPrint.addAction(self.actionPrint_Data_text)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.menuPrint.menuAction())
        self.menuEnvelops.addAction(self.actionBTF_Envelop)
        self.menuEnvelops.addAction(self.actionFint_Envelop)
        self.menuWindows.addAction(self.actionShowFiles)
        self.menuWindows.addAction(self.actionShowPlot)
        self.menuWindows.addAction(self.actionShowBTF)
        self.menuWindows.addAction(self.actionShowData)
        self.menuWindows.addAction(self.actionShowOpt)
        self.menuWindows.addAction(self.menuEnvelops.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())

        self.retranslateUi(BirdWindow)
        QtCore.QMetaObject.connectSlotsByName(BirdWindow)

    def retranslateUi(self, BirdWindow):
        BirdWindow.setWindowTitle(_translate("BirdWindow", "CuteBird v1.1.2", None))
        self.showFilesButton.setText(_translate("BirdWindow", "Files...", None))
        self.showPlotButton.setText(_translate("BirdWindow", "Plot...", None))
        self.showBtfButton.setText(_translate("BirdWindow", "BTF...", None))
        self.smallCalcButton.setText(_translate("BirdWindow", "Calculate", None))
        self.showDataButton.setText(_translate("BirdWindow", "Data...", None))
        self.showOptButton.setText(_translate("BirdWindow", "Optimize...", None))
        self.enrPlusButton.setText(_translate("BirdWindow", "Enr+", None))
        self.enrMinusButton.setText(_translate("BirdWindow", "Enr-", None))
        self.btfEnvelopLabel.setText(_translate("BirdWindow", "BTF Envelop:", None))
        self.fintEnvelopLabel.setText(_translate("BirdWindow", "FINT Envelop:", None))
        self.bowLabel.setText(_translate("BirdWindow", "Channel Bow:", None))
        self.vhiLabel.setText(_translate("BirdWindow", "Vhist", None))
        self.voiLabel.setText(_translate("BirdWindow", "Void", None))
        self.expLabel.setText(_translate("BirdWindow", "Exp", None))
        self.menuFile.setTitle(_translate("BirdWindow", "File", None))
        self.menuPrint.setTitle(_translate("BirdWindow", "Print", None))
        self.menuWindows.setTitle(_translate("BirdWindow", "Windows", None))
        self.menuEnvelops.setTitle(_translate("BirdWindow", "Envelops", None))
        self.actionExit.setText(_translate("BirdWindow", "Exit", None))
        self.actionShowFiles.setText(_translate("BirdWindow", "Files", None))
        self.actionShowPlot.setText(_translate("BirdWindow", "Plot", None))
        self.actionShowBTF.setText(_translate("BirdWindow", "BTF", None))
        self.actionShowData.setText(_translate("BirdWindow", "Data", None))
        self.actionShowOpt.setText(_translate("BirdWindow", "Optimize", None))
        self.actionBTF_Envelop.setText(_translate("BirdWindow", "BTF Envelop", None))
        self.actionFint_Envelop.setText(_translate("BirdWindow", "Fint Envelop", None))
        self.actionPrint.setText(_translate("BirdWindow", "Print", None))
        self.actionPrint_Pin_Layout.setText(_translate("BirdWindow", "Print Pin Layout", None))
        self.actionPrint_Diagram.setText(_translate("BirdWindow", "Print Diagram", None))
        self.actionPrint_Data_text.setText(_translate("BirdWindow", "Print Data text", None))

from cellCanvas import CellCanvas
from pointSpinBox import PointSpinBox
import CuteBird_rc
