# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataPopup.ui'
#
# Created: Wed Sep 23 20:32:22 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DataPopup(object):
    def setupUi(self, DataPopup):
        DataPopup.setObjectName(_fromUtf8("DataPopup"))
        DataPopup.resize(588, 361)
        self.verticalLayout = QtGui.QVBoxLayout(DataPopup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.datatTabWidget = QtGui.QTabWidget(DataPopup)
        self.datatTabWidget.setMinimumSize(QtCore.QSize(500, 300))
        self.datatTabWidget.setObjectName(_fromUtf8("datatTabWidget"))
        self.dataTab = QtGui.QWidget()
        self.dataTab.setObjectName(_fromUtf8("dataTab"))
        self.datatTabWidget.addTab(self.dataTab, _fromUtf8(""))
        self.boxBowTab = QtGui.QWidget()
        self.boxBowTab.setObjectName(_fromUtf8("boxBowTab"))
        self.datatTabWidget.addTab(self.boxBowTab, _fromUtf8(""))
        self.enrichTab = QtGui.QWidget()
        self.enrichTab.setObjectName(_fromUtf8("enrichTab"))
        self.datatTabWidget.addTab(self.enrichTab, _fromUtf8(""))
        self.weightTab = QtGui.QWidget()
        self.weightTab.setObjectName(_fromUtf8("weightTab"))
        self.datatTabWidget.addTab(self.weightTab, _fromUtf8(""))
        self.costTab = QtGui.QWidget()
        self.costTab.setObjectName(_fromUtf8("costTab"))
        self.datatTabWidget.addTab(self.costTab, _fromUtf8(""))
        self.costParaTab = QtGui.QWidget()
        self.costParaTab.setObjectName(_fromUtf8("costParaTab"))
        self.layoutWidget = QtGui.QWidget(self.costParaTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 5, 391, 161))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.uranCostLabel = QtGui.QLabel(self.layoutWidget)
        self.uranCostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uranCostLabel.setIndent(0)
        self.uranCostLabel.setObjectName(_fromUtf8("uranCostLabel"))
        self.gridLayout.addWidget(self.uranCostLabel, 0, 0, 1, 1)
        self.uranCostSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.uranCostSpinBox.setMaximum(9999)
        self.uranCostSpinBox.setSingleStep(10)
        self.uranCostSpinBox.setProperty("value", 800)
        self.uranCostSpinBox.setObjectName(_fromUtf8("uranCostSpinBox"))
        self.gridLayout.addWidget(self.uranCostSpinBox, 0, 1, 1, 1)
        self.uranRentalLabel = QtGui.QLabel(self.layoutWidget)
        self.uranRentalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uranRentalLabel.setObjectName(_fromUtf8("uranRentalLabel"))
        self.gridLayout.addWidget(self.uranRentalLabel, 0, 2, 1, 1)
        self.uranRentalSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.uranRentalSpinBox.setSingleStep(0.1)
        self.uranRentalSpinBox.setProperty("value", 7.0)
        self.uranRentalSpinBox.setObjectName(_fromUtf8("uranRentalSpinBox"))
        self.gridLayout.addWidget(self.uranRentalSpinBox, 0, 3, 1, 1)
        self.swuCostLabel = QtGui.QLabel(self.layoutWidget)
        self.swuCostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.swuCostLabel.setObjectName(_fromUtf8("swuCostLabel"))
        self.gridLayout.addWidget(self.swuCostLabel, 1, 0, 1, 1)
        self.swuCostSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.swuCostSpinBox.setMaximum(9999)
        self.swuCostSpinBox.setSingleStep(10)
        self.swuCostSpinBox.setProperty("value", 1800)
        self.swuCostSpinBox.setObjectName(_fromUtf8("swuCostSpinBox"))
        self.gridLayout.addWidget(self.swuCostSpinBox, 1, 1, 1, 1)
        self.swuRentalLabel = QtGui.QLabel(self.layoutWidget)
        self.swuRentalLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.swuRentalLabel.setObjectName(_fromUtf8("swuRentalLabel"))
        self.gridLayout.addWidget(self.swuRentalLabel, 1, 2, 1, 1)
        self.swuRentalSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.swuRentalSpinBox.setMaximum(100.0)
        self.swuRentalSpinBox.setSingleStep(0.1)
        self.swuRentalSpinBox.setProperty("value", 2.5)
        self.swuRentalSpinBox.setObjectName(_fromUtf8("swuRentalSpinBox"))
        self.gridLayout.addWidget(self.swuRentalSpinBox, 1, 3, 1, 1)
        self.fabricationCostLabel = QtGui.QLabel(self.layoutWidget)
        self.fabricationCostLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fabricationCostLabel.setObjectName(_fromUtf8("fabricationCostLabel"))
        self.gridLayout.addWidget(self.fabricationCostLabel, 2, 0, 1, 1)
        self.fabricationCostSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.fabricationCostSpinBox.setMaximum(9999)
        self.fabricationCostSpinBox.setSingleStep(10)
        self.fabricationCostSpinBox.setProperty("value", 2800)
        self.fabricationCostSpinBox.setObjectName(_fromUtf8("fabricationCostSpinBox"))
        self.gridLayout.addWidget(self.fabricationCostSpinBox, 2, 1, 1, 1)
        self.tailLabel = QtGui.QLabel(self.layoutWidget)
        self.tailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tailLabel.setMargin(0)
        self.tailLabel.setObjectName(_fromUtf8("tailLabel"))
        self.gridLayout.addWidget(self.tailLabel, 2, 2, 1, 1)
        self.tailSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.tailSpinBox.setMaximum(0.5)
        self.tailSpinBox.setSingleStep(0.05)
        self.tailSpinBox.setProperty("value", 0.25)
        self.tailSpinBox.setObjectName(_fromUtf8("tailSpinBox"))
        self.gridLayout.addWidget(self.tailSpinBox, 2, 3, 1, 1)
        self.burnupLabel = QtGui.QLabel(self.layoutWidget)
        self.burnupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.burnupLabel.setObjectName(_fromUtf8("burnupLabel"))
        self.gridLayout.addWidget(self.burnupLabel, 3, 0, 1, 1)
        self.burnupSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.burnupSpinBox.setProperty("value", 50)
        self.burnupSpinBox.setObjectName(_fromUtf8("burnupSpinBox"))
        self.gridLayout.addWidget(self.burnupSpinBox, 3, 1, 1, 1)
        self.termEfficiencyLabel = QtGui.QLabel(self.layoutWidget)
        self.termEfficiencyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.termEfficiencyLabel.setObjectName(_fromUtf8("termEfficiencyLabel"))
        self.gridLayout.addWidget(self.termEfficiencyLabel, 3, 2, 1, 1)
        self.termEfficiencyDoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.termEfficiencyDoubleSpinBox.setSingleStep(0.5)
        self.termEfficiencyDoubleSpinBox.setProperty("value", 34.0)
        self.termEfficiencyDoubleSpinBox.setObjectName(_fromUtf8("termEfficiencyDoubleSpinBox"))
        self.gridLayout.addWidget(self.termEfficiencyDoubleSpinBox, 3, 3, 1, 1)
        self.datatTabWidget.addTab(self.costParaTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.datatTabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fileNameLabel = QtGui.QLabel(DataPopup)
        self.fileNameLabel.setObjectName(_fromUtf8("fileNameLabel"))
        self.horizontalLayout.addWidget(self.fileNameLabel)
        self.fileNameLineEdit = QtGui.QLineEdit(DataPopup)
        self.fileNameLineEdit.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.fileNameLineEdit.setFont(font)
        self.fileNameLineEdit.setObjectName(_fromUtf8("fileNameLineEdit"))
        self.horizontalLayout.addWidget(self.fileNameLineEdit)
        self.printPushButton = QtGui.QPushButton(DataPopup)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/stock-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printPushButton.setIcon(icon)
        self.printPushButton.setObjectName(_fromUtf8("printPushButton"))
        self.horizontalLayout.addWidget(self.printPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DataPopup)
        self.datatTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(DataPopup)

    def retranslateUi(self, DataPopup):
        DataPopup.setWindowTitle(_translate("DataPopup", "Data popup for fuel data", None))
        self.datatTabWidget.setTabText(self.datatTabWidget.indexOf(self.dataTab), _translate("DataPopup", "Data", None))
        self.datatTabWidget.setTabText(self.datatTabWidget.indexOf(self.boxBowTab), _translate("DataPopup", "Bow", None))
        self.datatTabWidget.setTabText(self.datatTabWidget.indexOf(self.enrichTab), _translate("DataPopup", "Enrichments", None))
        self.datatTabWidget.setTabText(self.datatTabWidget.indexOf(self.weightTab), _translate("DataPopup", "Weight", None))
        self.datatTabWidget.setTabText(self.datatTabWidget.indexOf(self.costTab), _translate("DataPopup", "Cost", None))
        self.uranCostLabel.setText(_translate("DataPopup", "Nat uran cost (kr/kg):", None))
        self.uranRentalLabel.setText(_translate("DataPopup", "Rental (%):", None))
        self.swuCostLabel.setText(_translate("DataPopup", "SWU cost (kr/SWU):", None))
        self.swuRentalLabel.setText(_translate("DataPopup", "Rental (%):", None))
        self.fabricationCostLabel.setText(_translate("DataPopup", "Fabrication cost (kr/kg):", None))
        self.tailLabel.setText(_translate("DataPopup", "Tail (%):", None))
        self.burnupLabel.setText(_translate("DataPopup", "Burnup (MWd/kg):", None))
        self.termEfficiencyLabel.setText(_translate("DataPopup", "Th. eff (%):", None))
        self.datatTabWidget.setTabText(self.datatTabWidget.indexOf(self.costParaTab), _translate("DataPopup", "Cost parameters", None))
        self.fileNameLabel.setText(_translate("DataPopup", "File:", None))
        self.printPushButton.setText(_translate("DataPopup", "Print", None))

