# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesPopup.ui'
#
# Created: Wed Sep 23 20:43:34 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FilesPopup(object):
    def setupUi(self, FilesPopup):
        FilesPopup.setObjectName(_fromUtf8("FilesPopup"))
        FilesPopup.resize(679, 691)
        self.verticalLayout_5 = QtGui.QVBoxLayout(FilesPopup)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.closeButton = QtGui.QPushButton(FilesPopup)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.hboxlayout.addWidget(self.closeButton)
        spacerItem = QtGui.QSpacerItem(131, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.readBisFilesCheckBox = QtGui.QCheckBox(FilesPopup)
        self.readBisFilesCheckBox.setObjectName(_fromUtf8("readBisFilesCheckBox"))
        self.hboxlayout.addWidget(self.readBisFilesCheckBox)
        self.readAllVoidsCheckBox = QtGui.QCheckBox(FilesPopup)
        self.readAllVoidsCheckBox.setObjectName(_fromUtf8("readAllVoidsCheckBox"))
        self.hboxlayout.addWidget(self.readAllVoidsCheckBox)
        self.browseButton = QtGui.QPushButton(FilesPopup)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.hboxlayout.addWidget(self.browseButton)
        self.readFileButton = QtGui.QPushButton(FilesPopup)
        self.readFileButton.setObjectName(_fromUtf8("readFileButton"))
        self.hboxlayout.addWidget(self.readFileButton)
        self.verticalLayout_5.addLayout(self.hboxlayout)
        self.simFuelFileGroupBox = QtGui.QGroupBox(FilesPopup)
        self.simFuelFileGroupBox.setObjectName(_fromUtf8("simFuelFileGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.simFuelFileGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.simFuelLineWidget = FileLineWidget(self.simFuelFileGroupBox)
        self.simFuelLineWidget.setObjectName(_fromUtf8("simFuelLineWidget"))
        self.verticalLayout_4.addWidget(self.simFuelLineWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.readSimFuelButton = QtGui.QPushButton(self.simFuelFileGroupBox)
        self.readSimFuelButton.setObjectName(_fromUtf8("readSimFuelButton"))
        self.horizontalLayout_6.addWidget(self.readSimFuelButton)
        self.fuelTypeNftLabel = QtGui.QLabel(self.simFuelFileGroupBox)
        self.fuelTypeNftLabel.setMinimumSize(QtCore.QSize(90, 0))
        self.fuelTypeNftLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fuelTypeNftLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fuelTypeNftLabel.setObjectName(_fromUtf8("fuelTypeNftLabel"))
        self.horizontalLayout_6.addWidget(self.fuelTypeNftLabel)
        self.fuelTypeNftComboBox = QtGui.QComboBox(self.simFuelFileGroupBox)
        self.fuelTypeNftComboBox.setObjectName(_fromUtf8("fuelTypeNftComboBox"))
        self.horizontalLayout_6.addWidget(self.fuelTypeNftComboBox)
        self.fuelTypeIdentLabel = QtGui.QLabel(self.simFuelFileGroupBox)
        self.fuelTypeIdentLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.fuelTypeIdentLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fuelTypeIdentLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fuelTypeIdentLabel.setObjectName(_fromUtf8("fuelTypeIdentLabel"))
        self.horizontalLayout_6.addWidget(self.fuelTypeIdentLabel)
        self.fuelTypeIdentComboBox = QtGui.QComboBox(self.simFuelFileGroupBox)
        self.fuelTypeIdentComboBox.setObjectName(_fromUtf8("fuelTypeIdentComboBox"))
        self.horizontalLayout_6.addWidget(self.fuelTypeIdentComboBox)
        self.readThisCaseButton = QtGui.QPushButton(self.simFuelFileGroupBox)
        self.readThisCaseButton.setObjectName(_fromUtf8("readThisCaseButton"))
        self.horizontalLayout_6.addWidget(self.readThisCaseButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.segmentLineEdit = QtGui.QLineEdit(self.simFuelFileGroupBox)
        self.segmentLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.segmentLineEdit.setObjectName(_fromUtf8("segmentLineEdit"))
        self.verticalLayout_4.addWidget(self.segmentLineEdit)
        self.verticalLayout_5.addWidget(self.simFuelFileGroupBox)
        self.casmoFileGroupBox = QtGui.QGroupBox(FilesPopup)
        self.casmoFileGroupBox.setObjectName(_fromUtf8("casmoFileGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.casmoFileGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.fileLabel = QtGui.QLabel(self.casmoFileGroupBox)
        self.fileLabel.setMinimumSize(QtCore.QSize(74, 0))
        self.fileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.horizontalLayout_5.addWidget(self.fileLabel)
        self.fileLineEdit = QtGui.QLineEdit(self.casmoFileGroupBox)
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.horizontalLayout_5.addWidget(self.fileLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.fuelIdentLabel = QtGui.QLabel(self.casmoFileGroupBox)
        self.fuelIdentLabel.setMinimumSize(QtCore.QSize(74, 0))
        self.fuelIdentLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fuelIdentLabel.setObjectName(_fromUtf8("fuelIdentLabel"))
        self.hboxlayout1.addWidget(self.fuelIdentLabel)
        self.fuelIdentLineEdit = QtGui.QLineEdit(self.casmoFileGroupBox)
        self.fuelIdentLineEdit.setMaximumSize(QtCore.QSize(110, 16777215))
        self.fuelIdentLineEdit.setObjectName(_fromUtf8("fuelIdentLineEdit"))
        self.hboxlayout1.addWidget(self.fuelIdentLineEdit)
        self.topDirLabel = QtGui.QLabel(self.casmoFileGroupBox)
        self.topDirLabel.setObjectName(_fromUtf8("topDirLabel"))
        self.hboxlayout1.addWidget(self.topDirLabel)
        self.topdirLineEdit = QtGui.QLineEdit(self.casmoFileGroupBox)
        self.topdirLineEdit.setObjectName(_fromUtf8("topdirLineEdit"))
        self.hboxlayout1.addWidget(self.topdirLineEdit)
        self.verticalLayout_3.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem1)
        self.showCaiButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.showCaiButton.setObjectName(_fromUtf8("showCaiButton"))
        self.hboxlayout2.addWidget(self.showCaiButton)
        self.showCaoButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.showCaoButton.setObjectName(_fromUtf8("showCaoButton"))
        self.hboxlayout2.addWidget(self.showCaoButton)
        self.showCaxButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.showCaxButton.setObjectName(_fromUtf8("showCaxButton"))
        self.hboxlayout2.addWidget(self.showCaxButton)
        self.showPhiButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.showPhiButton.setObjectName(_fromUtf8("showPhiButton"))
        self.hboxlayout2.addWidget(self.showPhiButton)
        self.showPhxButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.showPhxButton.setObjectName(_fromUtf8("showPhxButton"))
        self.hboxlayout2.addWidget(self.showPhxButton)
        self.showSlxButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.showSlxButton.setObjectName(_fromUtf8("showSlxButton"))
        self.hboxlayout2.addWidget(self.showSlxButton)
        self.verticalLayout_3.addLayout(self.hboxlayout2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fillLabel = QtGui.QLabel(self.casmoFileGroupBox)
        self.fillLabel.setMinimumSize(QtCore.QSize(74, 0))
        self.fillLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fillLabel.setObjectName(_fromUtf8("fillLabel"))
        self.horizontalLayout.addWidget(self.fillLabel)
        self.fillComboBox = QtGui.QComboBox(self.casmoFileGroupBox)
        self.fillComboBox.setObjectName(_fromUtf8("fillComboBox"))
        self.horizontalLayout.addWidget(self.fillComboBox)
        self.fillButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.fillButton.setObjectName(_fromUtf8("fillButton"))
        self.horizontalLayout.addWidget(self.fillButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.dataPopupButton = QtGui.QPushButton(self.casmoFileGroupBox)
        self.dataPopupButton.setObjectName(_fromUtf8("dataPopupButton"))
        self.horizontalLayout.addWidget(self.dataPopupButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.casmoFileGroupBox)
        self.startCasmoGroupBox = QtGui.QGroupBox(FilesPopup)
        self.startCasmoGroupBox.setObjectName(_fromUtf8("startCasmoGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.startCasmoGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.oneVoidRadioButton = QtGui.QRadioButton(self.startCasmoGroupBox)
        self.oneVoidRadioButton.setObjectName(_fromUtf8("oneVoidRadioButton"))
        self.gridLayout.addWidget(self.oneVoidRadioButton, 0, 0, 1, 1)
        self.allVoidsRadioButton = QtGui.QRadioButton(self.startCasmoGroupBox)
        self.allVoidsRadioButton.setObjectName(_fromUtf8("allVoidsRadioButton"))
        self.gridLayout.addWidget(self.allVoidsRadioButton, 0, 1, 1, 1)
        self.coeffsCheckBox = QtGui.QCheckBox(self.startCasmoGroupBox)
        self.coeffsCheckBox.setObjectName(_fromUtf8("coeffsCheckBox"))
        self.gridLayout.addWidget(self.coeffsCheckBox, 0, 2, 1, 1)
        self.conrodLabel = QtGui.QLabel(self.startCasmoGroupBox)
        self.conrodLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.conrodLabel.setObjectName(_fromUtf8("conrodLabel"))
        self.gridLayout.addWidget(self.conrodLabel, 0, 3, 1, 1)
        self.conrodComboBox = QtGui.QComboBox(self.startCasmoGroupBox)
        self.conrodComboBox.setObjectName(_fromUtf8("conrodComboBox"))
        self.conrodComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.conrodComboBox, 0, 4, 1, 1)
        self.programLabel = QtGui.QLabel(self.startCasmoGroupBox)
        self.programLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.programLabel.setObjectName(_fromUtf8("programLabel"))
        self.gridLayout.addWidget(self.programLabel, 0, 5, 1, 1)
        self.programChoice = ProgramChoice(self.startCasmoGroupBox)
        self.programChoice.setObjectName(_fromUtf8("programChoice"))
        self.gridLayout.addWidget(self.programChoice, 0, 6, 1, 1)
        self.s3cRadioButton = QtGui.QRadioButton(self.startCasmoGroupBox)
        self.s3cRadioButton.setObjectName(_fromUtf8("s3cRadioButton"))
        self.gridLayout.addWidget(self.s3cRadioButton, 1, 0, 1, 1)
        self.s3cFastRadioButton = QtGui.QRadioButton(self.startCasmoGroupBox)
        self.s3cFastRadioButton.setObjectName(_fromUtf8("s3cFastRadioButton"))
        self.gridLayout.addWidget(self.s3cFastRadioButton, 1, 1, 1, 1)
        self.cclCheckBox = QtGui.QCheckBox(self.startCasmoGroupBox)
        self.cclCheckBox.setObjectName(_fromUtf8("cclCheckBox"))
        self.gridLayout.addWidget(self.cclCheckBox, 1, 2, 1, 1)
        self.voidLabel = QtGui.QLabel(self.startCasmoGroupBox)
        self.voidLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voidLabel.setObjectName(_fromUtf8("voidLabel"))
        self.gridLayout.addWidget(self.voidLabel, 1, 3, 1, 1)
        self.voidComboBox = QtGui.QComboBox(self.startCasmoGroupBox)
        self.voidComboBox.setObjectName(_fromUtf8("voidComboBox"))
        self.voidComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.voidComboBox, 1, 4, 1, 1)
        self.versionLabel = QtGui.QLabel(self.startCasmoGroupBox)
        self.versionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.gridLayout.addWidget(self.versionLabel, 1, 5, 1, 1)
        self.versionChoice = VersionChoice(self.startCasmoGroupBox)
        self.versionChoice.setObjectName(_fromUtf8("versionChoice"))
        self.gridLayout.addWidget(self.versionChoice, 1, 6, 1, 1)
        self.s3kRadioButton = QtGui.QRadioButton(self.startCasmoGroupBox)
        self.s3kRadioButton.setObjectName(_fromUtf8("s3kRadioButton"))
        self.gridLayout.addWidget(self.s3kRadioButton, 2, 0, 1, 1)
        self.s3kFastRadioButton = QtGui.QRadioButton(self.startCasmoGroupBox)
        self.s3kFastRadioButton.setObjectName(_fromUtf8("s3kFastRadioButton"))
        self.gridLayout.addWidget(self.s3kFastRadioButton, 2, 1, 1, 1)
        self.overwriteCheckBox = QtGui.QCheckBox(self.startCasmoGroupBox)
        self.overwriteCheckBox.setObjectName(_fromUtf8("overwriteCheckBox"))
        self.gridLayout.addWidget(self.overwriteCheckBox, 2, 2, 1, 1)
        self.burnupLabel = QtGui.QLabel(self.startCasmoGroupBox)
        self.burnupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.burnupLabel.setObjectName(_fromUtf8("burnupLabel"))
        self.gridLayout.addWidget(self.burnupLabel, 2, 3, 1, 1)
        self.burnupComboBox = QtGui.QComboBox(self.startCasmoGroupBox)
        self.burnupComboBox.setObjectName(_fromUtf8("burnupComboBox"))
        self.burnupComboBox.addItem(_fromUtf8(""))
        self.burnupComboBox.addItem(_fromUtf8(""))
        self.burnupComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.burnupComboBox, 2, 4, 1, 1)
        self.cpuLabel = QtGui.QLabel(self.startCasmoGroupBox)
        self.cpuLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cpuLabel.setObjectName(_fromUtf8("cpuLabel"))
        self.gridLayout.addWidget(self.cpuLabel, 2, 5, 1, 1)
        self.cpuChoice = CpuChoice(self.startCasmoGroupBox)
        self.cpuChoice.setObjectName(_fromUtf8("cpuChoice"))
        self.gridLayout.addWidget(self.cpuChoice, 2, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.writeInputButton = QtGui.QPushButton(self.startCasmoGroupBox)
        self.writeInputButton.setObjectName(_fromUtf8("writeInputButton"))
        self.verticalLayout.addWidget(self.writeInputButton)
        self.startProgramButton = QtGui.QPushButton(self.startCasmoGroupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/start_run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startProgramButton.setIcon(icon)
        self.startProgramButton.setObjectName(_fromUtf8("startProgramButton"))
        self.verticalLayout.addWidget(self.startProgramButton)
        self.consoleButton = QtGui.QPushButton(self.startCasmoGroupBox)
        self.consoleButton.setObjectName(_fromUtf8("consoleButton"))
        self.verticalLayout.addWidget(self.consoleButton)
        self.showOutputButton = QtGui.QPushButton(self.startCasmoGroupBox)
        self.showOutputButton.setObjectName(_fromUtf8("showOutputButton"))
        self.verticalLayout.addWidget(self.showOutputButton)
        spacerItem3 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.fileList = QtGui.QListWidget(self.startCasmoGroupBox)
        self.fileList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileList.setObjectName(_fromUtf8("fileList"))
        self.horizontalLayout_2.addWidget(self.fileList)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.startCasmoGroupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.writeDefaultButton = QtGui.QPushButton(FilesPopup)
        self.writeDefaultButton.setObjectName(_fromUtf8("writeDefaultButton"))
        self.horizontalLayout_3.addWidget(self.writeDefaultButton)
        self.readDefaultButton = QtGui.QPushButton(FilesPopup)
        self.readDefaultButton.setObjectName(_fromUtf8("readDefaultButton"))
        self.horizontalLayout_3.addWidget(self.readDefaultButton)
        self.writeQaButton = QtGui.QPushButton(FilesPopup)
        self.writeQaButton.setObjectName(_fromUtf8("writeQaButton"))
        self.horizontalLayout_3.addWidget(self.writeQaButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(FilesPopup)
        QtCore.QMetaObject.connectSlotsByName(FilesPopup)

    def retranslateUi(self, FilesPopup):
        FilesPopup.setWindowTitle(_translate("FilesPopup", "Files Popup", None))
        self.closeButton.setText(_translate("FilesPopup", "Close", None))
        self.readBisFilesCheckBox.setText(_translate("FilesPopup", "Read-bis files", None))
        self.readAllVoidsCheckBox.setText(_translate("FilesPopup", "Read all voids", None))
        self.browseButton.setText(_translate("FilesPopup", "Browse", None))
        self.readFileButton.setText(_translate("FilesPopup", "Read", None))
        self.simFuelFileGroupBox.setTitle(_translate("FilesPopup", "Simulate fuel description file (with FUE.ZON and SEG.LIB)", None))
        self.readSimFuelButton.setText(_translate("FilesPopup", "Read fuel descriptions", None))
        self.fuelTypeNftLabel.setText(_translate("FilesPopup", "FUE.ZON NFT:", None))
        self.fuelTypeIdentLabel.setText(_translate("FilesPopup", "FUE.ZON Ident:", None))
        self.readThisCaseButton.setText(_translate("FilesPopup", "Read cax-files", None))
        self.casmoFileGroupBox.setTitle(_translate("FilesPopup", "Casmo File", None))
        self.fileLabel.setText(_translate("FilesPopup", "File name:", None))
        self.fuelIdentLabel.setText(_translate("FilesPopup", "Fuel ident:", None))
        self.topDirLabel.setText(_translate("FilesPopup", "Directory:", None))
        self.showCaiButton.setText(_translate("FilesPopup", "Show cai", None))
        self.showCaoButton.setText(_translate("FilesPopup", "Show cao", None))
        self.showCaxButton.setText(_translate("FilesPopup", "Show cax", None))
        self.showPhiButton.setText(_translate("FilesPopup", "Show phi", None))
        self.showPhxButton.setText(_translate("FilesPopup", "Show phx", None))
        self.showSlxButton.setText(_translate("FilesPopup", "Show slx", None))
        self.fillLabel.setText(_translate("FilesPopup", "Fill type:", None))
        self.fillButton.setText(_translate("FilesPopup", "Fill tables", None))
        self.dataPopupButton.setText(_translate("FilesPopup", "Data...", None))
        self.startCasmoGroupBox.setTitle(_translate("FilesPopup", "Start Casmo", None))
        self.oneVoidRadioButton.setText(_translate("FilesPopup", "One void", None))
        self.allVoidsRadioButton.setText(_translate("FilesPopup", "v00/40/80", None))
        self.coeffsCheckBox.setText(_translate("FilesPopup", "Coeffs", None))
        self.conrodLabel.setText(_translate("FilesPopup", "Conrod:", None))
        self.conrodComboBox.setItemText(0, _translate("FilesPopup", "All", None))
        self.programLabel.setText(_translate("FilesPopup", "Program:", None))
        self.s3cRadioButton.setText(_translate("FilesPopup", "S3C", None))
        self.s3cFastRadioButton.setText(_translate("FilesPopup", "S3C Fast", None))
        self.cclCheckBox.setText(_translate("FilesPopup", "CCL", None))
        self.voidLabel.setText(_translate("FilesPopup", "Void:", None))
        self.voidComboBox.setItemText(0, _translate("FilesPopup", "All", None))
        self.versionLabel.setText(_translate("FilesPopup", "Version:", None))
        self.s3kRadioButton.setText(_translate("FilesPopup", "S3K", None))
        self.s3kFastRadioButton.setText(_translate("FilesPopup", "S3K Fast", None))
        self.overwriteCheckBox.setText(_translate("FilesPopup", "Overwrite", None))
        self.burnupLabel.setText(_translate("FilesPopup", "Burnup:", None))
        self.burnupComboBox.setItemText(0, _translate("FilesPopup", "e25", None))
        self.burnupComboBox.setItemText(1, _translate("FilesPopup", "e50", None))
        self.burnupComboBox.setItemText(2, _translate("FilesPopup", "e70", None))
        self.cpuLabel.setText(_translate("FilesPopup", "Cpu:", None))
        self.writeInputButton.setText(_translate("FilesPopup", "Write input", None))
        self.startProgramButton.setText(_translate("FilesPopup", "Start", None))
        self.consoleButton.setText(_translate("FilesPopup", "Console", None))
        self.showOutputButton.setText(_translate("FilesPopup", "Output", None))
        self.writeDefaultButton.setText(_translate("FilesPopup", "Write default", None))
        self.readDefaultButton.setText(_translate("FilesPopup", "Read default", None))
        self.writeQaButton.setText(_translate("FilesPopup", "Write QA", None))

from comboChoice import ProgramChoice, VersionChoice, CpuChoice
from fileLineWidget import FileLineWidget
import CuteBird_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FilesPopup = QtGui.QDialog()
    ui = Ui_FilesPopup()
    ui.setupUi(FilesPopup)
    FilesPopup.show()
    sys.exit(app.exec_())

