# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesPopup.ui'
#
# Created: Wed Sep 23 20:43:58 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(515, 420)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 41, 451, 338))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.widget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem = QtGui.QSpacerItem(131, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.browseButton = QtGui.QPushButton(self.widget)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.hboxlayout.addWidget(self.browseButton)
        self.readFileButton = QtGui.QPushButton(self.widget)
        self.readFileButton.setObjectName(_fromUtf8("readFileButton"))
        self.hboxlayout.addWidget(self.readFileButton)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.fileLabel = QtGui.QLabel(self.widget)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.hboxlayout1.addWidget(self.fileLabel)
        self.fileLineEdit = QtGui.QLineEdit(self.widget)
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.hboxlayout1.addWidget(self.fileLineEdit)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.fuelIdentLabel = QtGui.QLabel(self.widget)
        self.fuelIdentLabel.setObjectName(_fromUtf8("fuelIdentLabel"))
        self.hboxlayout2.addWidget(self.fuelIdentLabel)
        self.fuelIdentLineEdit = QtGui.QLineEdit(self.widget)
        self.fuelIdentLineEdit.setObjectName(_fromUtf8("fuelIdentLineEdit"))
        self.hboxlayout2.addWidget(self.fuelIdentLineEdit)
        self.topDirLabel = QtGui.QLabel(self.widget)
        self.topDirLabel.setObjectName(_fromUtf8("topDirLabel"))
        self.hboxlayout2.addWidget(self.topDirLabel)
        self.topDirLineEdit = QtGui.QLineEdit(self.widget)
        self.topDirLineEdit.setObjectName(_fromUtf8("topDirLineEdit"))
        self.hboxlayout2.addWidget(self.topDirLineEdit)
        self.vboxlayout.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem1)
        self.showCaiButton = QtGui.QPushButton(self.widget)
        self.showCaiButton.setObjectName(_fromUtf8("showCaiButton"))
        self.hboxlayout3.addWidget(self.showCaiButton)
        self.showCaoButton = QtGui.QPushButton(self.widget)
        self.showCaoButton.setObjectName(_fromUtf8("showCaoButton"))
        self.hboxlayout3.addWidget(self.showCaoButton)
        self.showCaxButton = QtGui.QPushButton(self.widget)
        self.showCaxButton.setObjectName(_fromUtf8("showCaxButton"))
        self.hboxlayout3.addWidget(self.showCaxButton)
        self.showSlxButton = QtGui.QPushButton(self.widget)
        self.showSlxButton.setObjectName(_fromUtf8("showSlxButton"))
        self.hboxlayout3.addWidget(self.showSlxButton)
        self.vboxlayout.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.oneVoidRadioButton = QtGui.QRadioButton(self.widget)
        self.oneVoidRadioButton.setObjectName(_fromUtf8("oneVoidRadioButton"))
        self.vboxlayout1.addWidget(self.oneVoidRadioButton)
        self.allVoidsRadioButton = QtGui.QRadioButton(self.widget)
        self.allVoidsRadioButton.setObjectName(_fromUtf8("allVoidsRadioButton"))
        self.vboxlayout1.addWidget(self.allVoidsRadioButton)
        self.s3cRadioButton = QtGui.QRadioButton(self.widget)
        self.s3cRadioButton.setObjectName(_fromUtf8("s3cRadioButton"))
        self.vboxlayout1.addWidget(self.s3cRadioButton)
        self.s3kRadioButton = QtGui.QRadioButton(self.widget)
        self.s3kRadioButton.setObjectName(_fromUtf8("s3kRadioButton"))
        self.vboxlayout1.addWidget(self.s3kRadioButton)
        spacerItem2 = QtGui.QSpacerItem(31, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem2)
        self.hboxlayout4.addLayout(self.vboxlayout1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.coeffsCheckBox = QtGui.QCheckBox(self.widget)
        self.coeffsCheckBox.setObjectName(_fromUtf8("coeffsCheckBox"))
        self.vboxlayout2.addWidget(self.coeffsCheckBox)
        self.cclCheckBox = QtGui.QCheckBox(self.widget)
        self.cclCheckBox.setObjectName(_fromUtf8("cclCheckBox"))
        self.vboxlayout2.addWidget(self.cclCheckBox)
        self.overwriteCheckBox = QtGui.QCheckBox(self.widget)
        self.overwriteCheckBox.setObjectName(_fromUtf8("overwriteCheckBox"))
        self.vboxlayout2.addWidget(self.overwriteCheckBox)
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.vboxlayout2.addWidget(self.checkBox)
        spacerItem3 = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout2.addItem(spacerItem3)
        self.hboxlayout4.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.burnupLabel = QtGui.QLabel(self.widget)
        self.burnupLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.burnupLabel.setObjectName(_fromUtf8("burnupLabel"))
        self.gridlayout.addWidget(self.burnupLabel, 0, 0, 1, 1)
        self.burnupComboBox = QtGui.QComboBox(self.widget)
        self.burnupComboBox.setObjectName(_fromUtf8("burnupComboBox"))
        self.burnupComboBox.addItem(_fromUtf8(""))
        self.burnupComboBox.addItem(_fromUtf8(""))
        self.burnupComboBox.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.burnupComboBox, 0, 1, 1, 1)
        self.voidLabel = QtGui.QLabel(self.widget)
        self.voidLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voidLabel.setObjectName(_fromUtf8("voidLabel"))
        self.gridlayout.addWidget(self.voidLabel, 1, 0, 1, 1)
        self.voidComboBox = QtGui.QComboBox(self.widget)
        self.voidComboBox.setObjectName(_fromUtf8("voidComboBox"))
        self.voidComboBox.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.voidComboBox, 1, 1, 1, 1)
        self.vboxlayout3.addLayout(self.gridlayout)
        self.writeInputButton = QtGui.QPushButton(self.widget)
        self.writeInputButton.setObjectName(_fromUtf8("writeInputButton"))
        self.vboxlayout3.addWidget(self.writeInputButton)
        self.pushButton_1 = QtGui.QPushButton(self.widget)
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.vboxlayout3.addWidget(self.pushButton_1)
        self.startCasmoButton = QtGui.QPushButton(self.widget)
        self.startCasmoButton.setObjectName(_fromUtf8("startCasmoButton"))
        self.vboxlayout3.addWidget(self.startCasmoButton)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.vboxlayout3.addWidget(self.pushButton_2)
        self.hboxlayout4.addLayout(self.vboxlayout3)
        self.vboxlayout.addLayout(self.hboxlayout4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.browseButton.setText(_translate("Dialog", "Browse", None))
        self.readFileButton.setText(_translate("Dialog", "Read", None))
        self.fileLabel.setText(_translate("Dialog", "File name:", None))
        self.fuelIdentLabel.setText(_translate("Dialog", "Fuel ident:", None))
        self.topDirLabel.setText(_translate("Dialog", "Top directory:", None))
        self.showCaiButton.setText(_translate("Dialog", "Show input", None))
        self.showCaoButton.setText(_translate("Dialog", "Show output", None))
        self.showCaxButton.setText(_translate("Dialog", "Show cax", None))
        self.showSlxButton.setText(_translate("Dialog", "Show tables", None))
        self.oneVoidRadioButton.setText(_translate("Dialog", "One void", None))
        self.allVoidsRadioButton.setText(_translate("Dialog", "v00/40/80", None))
        self.s3cRadioButton.setText(_translate("Dialog", "S3C", None))
        self.s3kRadioButton.setText(_translate("Dialog", "S3K", None))
        self.coeffsCheckBox.setText(_translate("Dialog", "Coeffs", None))
        self.cclCheckBox.setText(_translate("Dialog", "CCL", None))
        self.overwriteCheckBox.setText(_translate("Dialog", "Overwrite", None))
        self.checkBox.setText(_translate("Dialog", "CheckBox", None))
        self.burnupLabel.setText(_translate("Dialog", "Burnup:", None))
        self.burnupComboBox.setItemText(0, _translate("Dialog", "e25", None))
        self.burnupComboBox.setItemText(1, _translate("Dialog", "e50", None))
        self.burnupComboBox.setItemText(2, _translate("Dialog", "e70", None))
        self.voidLabel.setText(_translate("Dialog", "Void:", None))
        self.voidComboBox.setItemText(0, _translate("Dialog", "All", None))
        self.writeInputButton.setText(_translate("Dialog", "Write input", None))
        self.pushButton_1.setText(_translate("Dialog", "PushButton", None))
        self.startCasmoButton.setText(_translate("Dialog", "Start Casmo", None))
        self.pushButton_2.setText(_translate("Dialog", "PushButton", None))

